services:
  app:
    image: okayu11/sample-spring-boot-2-app:latest
    pull_policy: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DOCKER_MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    networks:
      - backend

  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DBNAME}
      MYSQL_USER: ${DOCKER_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
