name: Build and Push Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-jar
          path: target/demo-0.0.1-SNAPSHOT.jar

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-jar
          path: target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            okayu11/sample-spring-boot-2-app:latest
            okayu11/sample-spring-boot-2-app:${{ github.sha }}
          cache-from: type=registry,ref=okayu11/sample-spring-boot-2-app:buildcache
          cache-to: type=registry,ref=okayu11/sample-spring-boot-2-app:buildcache,mode=max
